[package]
name = "asahi-bless"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "0.8"
gpt = "3"

[dependencies.nvram]
path = "../nvram"
